# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
