# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20160421_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='level',
            field=models.CharField(choices=[('Default', 'Default'), ('Supervisor', 'Supervisor')], default='Default', max_length=20),
        ),
    ]
