# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160421_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
