# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20161216_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
