# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20161216_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Activity'),
            preserve_default=False,
        ),
    ]
