# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_departmentverbs_personalverbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='percentageCompletion',
            field=models.IntegerField(default=0),
        ),
    ]
